name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users first issue'
        pr-message: 'Message that will be displayed on users first pull request'
        i have adjusted this bot to enable us have fun for all but some committed it to be banned, so kindly bare with the situation
again use the appropriate commands to enable us perform the actions accurately
kindly comply to the changes stated above to enable us do the necessary
